language: python

python:
- 2.7
- 3.5

env:
  - TOXENV=django111-drf37
  - TOXENV=django111-drf38
  - TOXENV=django111-drf39
  - TOXENV=django111-drflatest
  - TOXENV=django20-drf37
  - TOXENV=django20-drf38
  - TOXENV=django20-drf39
  - TOXENV=django20-drflatest
  - TOXENV=django21-drf37
  - TOXENV=django21-drf38
  - TOXENV=django21-drf39
  - TOXENV=django21-drflatest
  - TOXENV=django22-drf37
  - TOXENV=django22-drf38
  - TOXENV=django22-drf39
  - TOXENV=django22-drflatest

matrix:
  include:
  - python: 3.5
    env: TOXENV=quality
  - python: 3.5
    env: TOXENV=docs
  - python: 3.5
    env: TOXENV=pii_check
  exclude:
    - python: 2.7
      env: TOXENV=django20-drf37
    - python: 2.7
      env: TOXENV=django20-drf38
    - python: 2.7
      env: TOXENV=django20-drf39
    - python: 2.7
      env: TOXENV=django20-drflatest
    - python: 2.7
      env: TOXENV=django21-drf37
    - python: 2.7
      env: TOXENV=django21-drf38
    - python: 2.7
      env: TOXENV=django21-drf39
    - python: 2.7
      env: TOXENV=django21-drflatest
    - python: 2.7
      env: TOXENV=django22-drf37
    - python: 2.7
      env: TOXENV=django22-drf38
    - python: 2.7
      env: TOXENV=django22-drf39
    - python: 2.7
      env: TOXENV=django22-drflatest

cache:
- pip
before_install:
- pip install --upgrade pip
install:
- pip install -r requirements/travis.txt
script:
- tox
after_success:
- codecov
deploy:
  provider: pypi
  user: edx
  distributions: sdist bdist_wheel
  on:
    tags: true
    condition: "$TOXENV = quality"
  password:
    secure: VtcghD/ccaLfoQy0o1HdEnzuBdE1bwIG1PYd/Yn+xlUxDVD9piKqlq9Gt2XMDlvHdZ2y7QRqe474dZEUacb4kGZhLeBu1GublBGeQorDO0+5S35N2vX/kwtAICZjPx4ufSTn8qmq9eiQWTQcKP2NpPXEdrzdhJInMnUKp3vcOThMvaMz/iFVZ8iwyr+/30P1E050f8Mt1oTJmmrM0cMi7vN1oD9ej63A8dmLxZvVEM1phOTlCak90ki/b1OhCdml8iN5NEQimklaYza/8BwT3+O7uPkjz56LJPFO+amUVDSeh50s2Pw4+Np+OUtN4SBlMIWB+pezr+4h0UjphzyTMa+giGsN+0Se96D9AdSBO8SDFM6EVOos8WZNb/oBc9Ganx3GeC0M3taco7N6e/QaQY0Is8lD0LwnT1Ffojo/ACchG20Iq2kSSvB6Nd+BLfcR/pn6Mpu0LKlvQldus3Bs9oFlOqQ+jhmzTIuJSSbsQGkgu6BfgdMDdj6FKF4QuKZYiIObn4XOgpERsx7elxtowAhrPHeZEURiHCOhrlRf29oUFaaRQzMc0g/HlOU0qqNPjVVR6Dc9qLwc539eRJmQaHp/1+sLIpTBpidR+j7V44k4pzPv5nsCkqnjdTu4grb//rNTH1Q71DpoG20Dgk01ZiDIUWU5YVl6R88FvNt5kTU=
